### ISSUE TITLE
calculo angulo

### ISSUE THREAD

**Issue by arnaldojr** [lnbt07/nac01_pythonEOpenCV#1]
https://github.com/lnbt07/nac01_pythonEOpenCV/blob/6a7d25722889cbf61c61eb8deb0caa72c83f303b/webcamCirculos.py#L98

calculo do ângulo, quase correto. da uma olhada... 

angulo = math.atan2(cyV[0] - cyV[vetorTamanho-1], cxV[0] - cxV[vetorTamanho-1])

**Comment by lnbt07** [comment]
Corrigido o calculo do ângulo, obrigada pela ajuda! 
Admito que ainda travo um pouco com essas formulas kkkk
